#!/usr/bin/env node
/**
 * Generates the synthetic reference clips for the Phase 0 regression harness.
 *
 * These stand in for real recordings until the Katana clip library exists
 * (PLAN.md §11.3): chromatics/open strings, detuned variants, and a concert-A
 * reference. Real clips (recorded through the Katana over USB) can be dropped
 * into harness/clips/ and added to manifest.json alongside these.
 *
 * Run:  node harness/generate-clips.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const SAMPLE_RATE = 44100
const DURATION = 3.0
const AMPLITUDE = 0.5

const clipsDir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'clips')
mkdirSync(clipsDir, { recursive: true })

/** Frequency values in exact equal temperament (A4 = 440). */
const CLIPS = [
  { file: 'e2-open.wav', hz: 82.4069, note: 'E2', desc: 'low E open string — the 82 Hz requirement' },
  { file: 'a2-open.wav', hz: 110.0, note: 'A2', desc: 'A open string' },
  { file: 'd3-open.wav', hz: 146.8324, note: 'D3', desc: 'D open string' },
  { file: 'g3-open.wav', hz: 195.9977, note: 'G3', desc: 'G open string' },
  { file: 'b3-open.wav', hz: 246.9417, note: 'B3', desc: 'B open string' },
  { file: 'e4-open.wav', hz: 329.6276, note: 'E4', desc: 'high E open string' },
  { file: 'a4-440.wav', hz: 440.0, note: 'A4', desc: 'concert A reference' },
  { file: 'e2-sharp15.wav', hz: 83.1272, note: 'E2+15¢', desc: 'low E 15 cents sharp — no ET snapping' },
  { file: 'g3-flat20.wav', hz: 193.7447, note: 'G3−20¢', desc: 'G 20 cents flat — no ET snapping' },
  { file: 'e4-sharp30.wav', hz: 335.3653, note: 'E4+30¢', desc: 'high E 30 cents sharp — no ET snapping' },
]

/** Plucked-string-ish tone: harmonic stack, per-partial decay, pluck envelope. */
function synthClip(hz) {
  const n = Math.floor(SAMPLE_RATE * DURATION)
  const pcm = new Int16Array(n)
  const harmonics = [
    [1, 1.0],
    [2, 0.5],
    [3, 0.28],
    [4, 0.14],
    [5, 0.08],
  ]
  for (let i = 0; i < n; i++) {
    const t = i / SAMPLE_RATE
    let v = 0
    for (const [mult, amp] of harmonics) {
      // Higher partials decay faster, like a real pluck.
      const decay = Math.exp(-t * (1.1 + 0.5 * mult))
      v += amp * decay * Math.sin(2 * Math.PI * hz * mult * t)
    }
    // Fast attack, slow decay, short fade-out at the end.
    const attack = Math.min(1, t / 0.02)
    const release = t > DURATION - 0.05 ? Math.max(0, (DURATION - t) / 0.05) : 1
    const env = attack * Math.exp(-t * 0.35) * release
    const sample = Math.max(-1, Math.min(1, v * env * AMPLITUDE))
    pcm[i] = Math.round(sample * 32767)
  }
  return pcm
}

function writeWav(file, pcm) {
  const dataSize = pcm.length * 2
  const buf = Buffer.alloc(44 + dataSize)
  buf.write('RIFF', 0)
  buf.writeUInt32LE(36 + dataSize, 4)
  buf.write('WAVE', 8)
  buf.write('fmt ', 12)
  buf.writeUInt32LE(16, 16) // PCM chunk size
  buf.writeUInt16LE(1, 20) // PCM format
  buf.writeUInt16LE(1, 22) // mono
  buf.writeUInt32LE(SAMPLE_RATE, 24)
  buf.writeUInt32LE(SAMPLE_RATE * 2, 28) // byte rate
  buf.writeUInt16LE(2, 32) // block align
  buf.writeUInt16LE(16, 34) // bits per sample
  buf.write('data', 36)
  buf.writeUInt32LE(dataSize, 40)
  for (let i = 0; i < pcm.length; i++) buf.writeInt16LE(pcm[i], 44 + i * 2)
  writeFileSync(file, buf)
}

const manifest = {
  version: 1,
  description:
    'Reference clips for the Brutzo Phase 0 regression harness. Currently synthetic (generated by harness/generate-clips.mjs); real Katana-USB recordings get added here per PLAN.md §11.3.',
  generator: 'harness/generate-clips.mjs',
  clips: [],
}

for (const clip of CLIPS) {
  const pcm = synthClip(clip.hz)
  const file = path.join(clipsDir, clip.file)
  writeWav(file, pcm)
  manifest.clips.push({
    file: clip.file,
    expectedHz: clip.hz,
    expectedNote: clip.note,
    toleranceCents: 10,
    description: clip.desc,
  })
  console.log(`wrote ${file} (${clip.note}, ${clip.hz} Hz, ${DURATION}s)`)
}

writeFileSync(path.join(clipsDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n')
console.log(`wrote ${path.join(clipsDir, 'manifest.json')} (${manifest.clips.length} clips)`)
